openapi: 3.1.0
info:
  title: ValtioData plugin API
  version: "0.1"
  description: |
    Proxy ChatGPT-käyttöön. Välittää pyynnöt Suomen valtiontalous-rajapinnan
    budjettitaloudentapahtumat-endpointille.
servers:
  - url: https://valtion-budjetti-data.web.app
paths:
  /budjettidata:
    get:
      operationId: getBudgetData
      summary: Hakee budjettitalouden tapahtumia Tutkihallintoa-rajapinnasta.
      parameters:
        - name: yearFrom
          in: query
          description: Alkuvuosi (yyyy)
          required: false
          schema:
            type: integer
            minimum: 1998
        - name: yearTo
          in: query
          description: Loppuvuosi (yyyy)
          required: false
          schema:
            type: integer
            minimum: 1998
        - name: monthFrom
          in: query
          description: Alkukuukausi (1-12)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - name: monthTo
          in: query
          description: Loppukuukausi (1-12)
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 12
        - name: paaluokka
          in: query
          description: Talousarvion pääluokka (esim. 25 = OKM)
          required: false
          schema:
            type: integer
        - name: momentti
          in: query
          description: Talousarviomomentin koodi, esim. 29.10.30
          required: false
          schema:
            type: string
        - name: hallinnonala
          in: query
          description: Hallinnonalan koodi
          required: false
          schema:
            type: integer
        - name: tilivirasto
          in: query
          description: Tiliviraston koodi
          required: false
          schema:
            type: integer
      responses:
        "200":
          description: JSON-objekti Tutkihallintoa-rajapinnasta
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object